#
# Jekyll Settings
#

#production_url是sitemap.txt生成的url,方便百度谷歌收录
production_url: http://www.jediego.com/
name:           浮忆之窨
url:            http://www.jediego.com/

source:         .
destination:    ./_site
plugins_dir:        ./_plugins
highlighter:    pygments

#rdiscount解析器对于嵌入html javascript代码,为文章增加特定效果兼容较好
markdown:       rdiscount
permalink:      /:categories/:title #/:categories/:year/:month/:title

paginate_path:  "page/page:num"
paginate:       7
exclude:        [ "README.md",".idea",".iml",".name",".Node"]
markdown_ext:   markdown,mkd,mkdn,md
encoding:       utf-8

#在发布文章时使用一个未来的日期
future:         true

#产生相关页面的索引
lsi:            false

post_defaults:
  layout:       post

rdiscount:
  extensions:   [  "autolink" ]


